[workspace]
resolver = "2"
members = [
    "common-rust",
    "common-rust/macros",
    "cli",
    "resource-pack",
    "grpc-server",
    "grpc-server/common",
    "grpc-server/sql-macros",
    "rest-webserver",
    "rust-tools/lint"
]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1