[versions]
kotlin = "1.6.10"
minecraft = "1.18.1"
paperweight-userdev = "1.3.5-SNAPSHOT"
plugin-yml = "0.5.1"
purpur = "1.18.1-R0.1-SNAPSHOT"
coroutines = "1.6.0"
shadow = "7.1.2"
adventure = "4.9.3"
adventure-bukkit = "4.0.1"
minedown = "1.7.1-SNAPSHOT"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
purpur-api = { module = "org.purpurmc.purpur:purpur-api", version.ref = "purpur" }
aventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-bukkit-api = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-bukkit" }
minedown = { module = "de.themoep:minedown-adventure", version.ref = "minedown" }

[bundles]
kotlin-essential = ["kotlinx-coroutines", "kotlin-reflect"]
adventure = ["aventure-api", "adventure-bukkit-api"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
plugin-yml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "plugin-yml" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight-userdev" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }