[versions]
kotlin = "1.6.20-M1"
kotlinx-serialization = "1.3.2"
kaml = "0.40.0"
minecraft = "1.18.1"
paperweight-userdev = "1.3.5-SNAPSHOT"
plugin-yml = "0.5.1"
purpur = "1.18.1-R0.1-SNAPSHOT"
coroutines = "1.6.0"
shadow = "7.1.2"
adventure = "4.9.3"
minedown = "1.7.1-SNAPSHOT"
kotest = "5.1.0"
mockk = "1.12.2"
valiktor = "0.12.0"
run-paper = "1.0.6"
logback = "1.3.0-alpha14"
slf4j = "2.0.0-alpha6"
mordant = "2.0.0-beta4"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
valiktor-core = { module = "org.valiktor:valiktor-core", version.ref = "valiktor" }
# Minecraft
purpur-dev-bundle = { module = "org.purpurmc.purpur:dev-bundle", version.ref = "purpur" }
adventure-extra-kotlin = { module = "net.kyori:adventure-extra-kotlin", version.ref = "adventure" }
adventure-text-serializer-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure" }
minedown = { module = "de.themoep:minedown-adventure", version.ref = "minedown" }
# Testing
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
# Logging
mordant = { module = "com.github.ajalt.mordant:mordant", version.ref = "mordant" }

[bundles]
kotlin-essential = ["kotlinx-coroutines", "kotlin-reflect", "kotlinx-serialization-core", "kaml", "valiktor-core"]
adventure = ["adventure-text-serializer-plain", "adventure-extra-kotlin"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
plugin-yml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "plugin-yml" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight-userdev" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
