[package]
name = "hexalite_common"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
entity = []
rest = []
protocol = []

[dependencies]
tokio = { version = "^1.17", features = ["full"] }
futures = "^0.3"
home = "^0"
lazy_static = "^1"
prost = { version = "^0.10", features = ["prost-derive"] }
prost-types = "0.10"
bytes = "^1.1"
serde = { version = "^1", features = ["derive"] }
uuid = { version = "^0", features = ["v4", "serde"] }
chrono = { version = "^0.4", features  = ["serde"] }

[build-dependencies]
prost-build = "^0.10"
glob = "^0"
