[package]
name = "hexalite_common"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "^0"
lazy_static = "^1"
protobuf = "^3.0.0-alpha"

[build-dependencies]
protoc-bin-vendored = "^3"
protoc-rust = "^3.0.0-alpha"
glob = "^0.3"