version: '3'

services:
  database-container:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ~/.hexalite/postgresql/data:/var/lib/postgresql/data
    networks:
      - postgres-network
  redis-container:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ~/.hexalite/redis/data:/data
    networks:
      - redis-network
networks:
  postgres-network:
    driver: bridge
  redis-network:
    driver: bridge