edition = "2021"
newline_style = "Unix"
tab_spaces = 4
use_field_init_shorthand = true
match_block_trailing_comma = true
type_punctuation_density = "Wide"
use_try_shorthand = true
wrap_comments = false
trailing_comma = "Vertical"
struct_lit_single_line = true
reorder_modules = true
reorder_imports = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
normalize_comments = true
hard_tabs = false
format_code_in_doc_comments = true
imports_granularity = "Module"
merge_derives = true
match_arm_blocks = true
