version: '3'

services:
  discord-bot:
    container_name: voxeru-discord-bot
    network_mode: "host"
    build:
      context: ../../voxeru-discord-bot
      dockerfile: ../infrastructure/discord-bot/Dockerfile
      args:
        - SETTINGS_PROFILE=${SETTINGS_PROFILE:-southdust}
    environment:
      - DISCORD_AUTH_TOKEN=$DISCORD_AUTH_TOKEN
      - RUST_LOG=${RUST_LOG:-info}
    volumes:
      - type: bind
        source: ../../voxeru-discord-bot/settings.${SETTINGS_PROFILE}.json
        target: /settings.json
      - type: bind
        source: ../../voxeru-discord-bot/assets
        target: /assets
      - type: bind
        source: ../../voxeru-discord-bot/i18n
        target: /localisation