[package]
name = "hexalite"
publish = false
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^4"
sea-query = "^0"
chrono = "^0"
log = "^0"
fast_log = "^1"
sea-orm = { version = "^0", features = [ "sqlx-postgres", "runtime-actix-native-tls", "debug-print", "macros" ], default-features = false }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
tokio = "^1"
lapin = "^2"
redis = "^0"
jwt = "^0" 
toml = "^0"
lazy_static = "^1"
home = "^0"