[package]
name = "hexalite"
publish = false
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
chrono = "0.4"
log = "0.4"
fast_log = "1.5"
sea-orm = { version = "0.7", features = [ "sqlx-postgres", "runtime-actix-native-tls", "debug-print", "macros" ], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1.17"
lapin = "2.1"
redis = "0.21"
jwt = "0.16" 
toml = "0.5"
lazy_static = "1.4"
home = "0.5"