name: Rust CI with Cargo

on:
  push:
    branches: [ 'dev/next' ]
  pull_request:
    branches: [ 'dev/next' ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://johndoe:mysecretpassword@localhost:5432/hexalite

jobs:
  cargo-ubuntu-build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: johndoe
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: hexalite
        ports:
          - "5432:5432"
    steps:
      - uses: actions/checkout@v2
      - name: Use Cache
        uses: actions/cache@v2
        with: 
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            common-rust/target/
            resource-pack/target/
            rest-webserver/target/
            grpc-server/target/
            cli/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - uses: rui314/setup-mold@v1
      - uses: egor-tensin/setup-clang@v1
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - name: Check for code errors (Rust)
        uses: actions-rs/cargo@v1
        with:
          command: check