name: Rust CI with Cargo

on:
  push:
    branches: [ 'dev/next' ]
  pull_request:
    branches: [ 'dev/next' ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Cache
        uses: actions/cache@v2
        with: 
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            common-rust/target/
            resource-pack/target/
            rest-webserver/target/
            cli/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Build the webserver
        uses: actions-rs/cargo@v1
        with:
          command: build 
          args: --release --manifest-path rest-webserver/Cargo.toml 
      - name: Build the command-line interface
        uses: actions-rs/cargo@v1
        with:
          command: build 
          args: --release --manifest-path cli/Cargo.toml
      - name: Build the resource pack generator
        uses: actions-rs/cargo@v1
        with:
          command: build 
          args: --release --manifest-path resource-pack/Cargo.toml
      - name: Upload Cargo artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cargo-artifacts
          path: |
            ./rest-webserver/target/release/rest-webserver 
            ./cli/target/release/hexalite
