name: Kotlin CI with Gradle

on:
  push:
    branches: [ main, 'dev/next' ]
  pull_request:
    branches: [ main, 'dev/next' ]

jobs:
  gradle-ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Early-Access build of a named project from jdk.java.net'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: panama
      - uses: rui314/setup-mold@v1
      - uses: egor-tensin/setup-clang@v1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Use Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Check for code errors (Gradle)
        run: ./gradlew check


