name: Kotlin CI with Gradle

on:
  push:
    branches: [ main, 'dev/next' ]
  pull_request:
    branches: [ main, 'dev/next' ]

jobs:
  gradle-ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          download_url="https://download.java.net/java/early_access/panama/1/openjdk-19-panama+1-13_linux-x64_bin.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Use Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Check for code errors (Gradle)
        run: ./gradlew check


